### PR TITLE
Make `camp_zipnerf` importable

### PR DESCRIPTION
**Pull request by duckworthd**
This PR makes the necessary changes to turn `camp_zipnerf` into a library. After this change, `camp_zipnerf` can be (locally) installed similar to any other Python library,

```shell
# install pycolmap and its dependencies
...

# install camp_zipnerf and its dependencies
$ git clone https://github.com/jonbarron/camp_zipnerf.git
$ cd camp_zipnerf
$ pip install -e .

# import camp_zipnerf
$ python3
>>> from camp_zipnerf import internal as czlib
>>> czlib.utils.Rays  # <class 'camp._zipnerf.internal.utils.Rays'>
```

This PR includes the following changes,
- [x] `internal` -> `camp_zipnerf/internal`
- [x] `{train,eval,render}.py` -> `camp_zipnerf/{train,eval,render}.py`
- [x] `from internal import <module>` -> `from . import <module>`, `from .internal import <module>`, or `from camp_zipnerf.internal import <module>` as appropriate.
- [x] `README.md` updated with new installation instructions.
- [x] Added `pyproject.toml` to interact with `setuptools`. Removed contents of `requirements.txt` into this file.

The following has been verified,
- [x] Train scripts launch
- [x] Unit tests pass

**!! WARNING !!** This PR depends on https://github.com/rmbrualla/pycolmap/pull/1. Do not merge this before the other PR is merged!!

### CODE REVIEW

**Comment by jonbarron** [comment]
cool! Should I merge now or are you blocked on Ricardo?

**Comment by duckworthd** [comment]
I'm blocked on Ricardo. I recommend taking a quick read and checking if
anything seems amiss. Until this PR is merged, Peter and I can continue
iterating on it.

jonbarron ***@***.***> schrieb am Do., 18. Apr. 2024, 00:16:

**Comment by duckworthd** [comment]
@jonbarron >> https://github.com/rmbrualla/pycolmap/pull/1 has been merged! This PR is now ready to merge as well.

**Comment by duckworthd** [comment]
@jonbarron >> https://github.com/rmbrualla/pycolmap/pull/1 has been merged! This PR is now ready to merge as well.

**Pull request merged**
